In [2]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [3]:
dataset = pd.read_csv('PG_2006-01-01_to_2018-01-01.csv')
dataset = dataset.fillna(dataset.mean())

In [4]:
dataset.head()

Date   Open   High    Low  Close   Volume Name
0  2006-01-03  58.30  58.86  57.69  58.78  9741600   PG
1  2006-01-04  58.80  59.12  58.56  58.89  6746400   PG
2  2006-01-05  58.70  59.07  58.61  58.70  8936100   PG
3  2006-01-06  58.74  58.80  58.48  58.64  8826300   PG
4  2006-01-09  58.45  59.09  58.45  59.08  7715700   PG

In [5]:
X = dataset.iloc[:, 1:4].values
y = dataset.iloc[:, 4].values

In [6]:
X

array([[58.3 , 58.86, 57.69],
       [58.8 , 59.12, 58.56],
       [58.7 , 59.07, 58.61],
       ...,
       [92.49, 92.75, 91.93],
       [92.3 , 92.54, 91.91],
       [92.24, 92.46, 91.88]])

In [7]:
y

array([58.78, 58.89, 58.7 , ..., 92.1 , 92.07, 91.88])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [10]:
prediction = lr.predict(X_test)

In [11]:
prediction

array([69.64774829, 60.24175231, 81.5974651 , 75.3279847 , 60.9926401 ,
       60.06853419, 79.63173454, 63.80862013, 58.43382198, 61.5009372 ,
       75.27952357, 66.1563095 , 84.40541266, 78.97487775, 62.9704918 ,
       80.52691933, 65.94142527, 80.2768167 , 72.90281837, 67.40910089,
       63.27662128, 63.4166293 , 55.79153378, 88.05157779, 83.41065589,
       92.18681057, 70.04747491, 88.9840823 , 52.61104632, 62.85959614,
       68.42026082, 90.51586628, 63.33972654, 61.30752019, 76.69282346,
       63.41120669, 63.48543276, 90.99832994, 60.79224951, 63.02016101,
       83.21592088, 69.26527211, 66.6552314 , 64.02858913, 89.8802909 ,
       64.59151065, 65.90431836, 57.96921054, 63.88529483, 64.79187624,
       59.72598634, 72.06788584, 63.0927345 , 85.96875603, 81.99090399,
       68.04667627, 87.97215503, 74.06690916, 65.43637863, 63.04728965,
       83.90784317, 78.12446355, 57.16620137, 90.31197988, 59.94782116,
       60.35987643, 62.06618898, 64.38381122, 56.95897122, 76.65

In [12]:
len(X_train)

2416

In [13]:
len(y_train)

2416

In [14]:
len(lr.predict(X_train))

2416

In [15]:
print(X_train.shape)

(2416, 3)


In [16]:
print(y_train.shape)

(2416,)


In [17]:
import statsmodels.formula.api as sm
X_opt = X[:, [0, 1, 2]]
lin_reg_OLS = sm.OLS(endog = y, exog = X_opt).fit()
lin_reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 3.851e+07
Date:                Sun, 11 Aug 2019   Prob (F-statistic):               0.00
Time:                        04:17:30   Log-Likelihood:                -1259.4
No. Observations:                3020   AIC:                             2525.
Df Residuals:                    3017   BIC:                             2543.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.2933      0.015    -20.048      0.000      -0.322      -0.265
x2             0.9030      0.012     78.320      0.000       0.880       0.926
x3             0.3872      0.010     37.571      0.000       0.367       0.407
==============================================================================
Omnibus:                     1554.839   Durbin-Watson:                   1.861
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           385596.249
Skew:                           1.264   Prob(JB):                         0.00
Kurtosis:                      58.299   Cond. No.                         335.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 3.189e+07
Date:                Sun, 11 Aug 2019   Prob (F-statistic):               0.00
Time:                        04:05:06   Log-Likelihood:                -4387.3
No. Observations:                3020   AIC:                             8779.
Df Residuals:                    3018   BIC:                             8791.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0574      0.018      3.168      0.002       0.022       0.093
x2             0.9498      0.018     52.097      0.000       0.914       0.985
==============================================================================
Omnibus:                     1210.640   Durbin-Watson:                   1.725
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             6619.693
Skew:                           1.835   Prob(JB):                         0.00
Kurtosis:                       9.257   Cond. No.                         289.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""