In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [2]:
dataset = pd.read_csv('GOOGL_2006-01-01_to_2018-01-01.csv')
dataset = dataset.fillna(dataset.mean())

In [3]:
dataset.head()

Date    Open    High     Low   Close    Volume   Name
0  2006-01-03  211.47  218.05  209.32  217.83  13137450  GOOGL
1  2006-01-04  222.17  224.70  220.09  222.84  15292353  GOOGL
2  2006-01-05  223.22  226.00  220.97  225.85  10815661  GOOGL
3  2006-01-06  228.66  235.49  226.85  233.06  17759521  GOOGL
4  2006-01-09  233.44  236.94  230.70  233.68  12795837  GOOGL

In [4]:
X = dataset.iloc[:, 1:4].values
y = dataset.iloc[:, 4].values

In [5]:
X

array([[ 211.47,  218.05,  209.32],
       [ 222.17,  224.7 ,  220.09],
       [ 223.22,  226.  ,  220.97],
       ...,
       [1066.6 , 1068.27, 1058.38],
       [1062.25, 1064.84, 1053.38],
       [1055.49, 1058.05, 1052.7 ]])

In [6]:
y

array([ 217.83,  222.84,  225.85, ..., 1060.2 , 1055.95, 1053.4 ])

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [9]:
prediction = lr.predict(X_test)

In [10]:
prediction

array([ 242.99102112,  193.3181565 ,  740.56966449,  695.5591904 ,
        246.94360536,  224.92898636,  604.00059451,  303.07772713,
        226.14715207,  258.18360752,  384.23811276,  322.34749762,
        808.1968286 ,  545.21180175,  246.80070188,  560.62765388,
        316.93812747,  534.533923  ,  644.54259431,  352.94209397,
        289.29934023,  268.03005769,  246.84994679,  942.38615902,
        588.97157648,  997.1495437 ,  226.31815433,  989.53403227,
        228.82006488,  244.81987091,  367.56290318,  530.94144682,
        223.90058947,  156.9837537 ,  437.9548229 ,  280.69870826,
        261.72883563,  722.75909003,  266.59522021,  277.91497409,
        760.27665362,  364.13170231,  334.70225914,  240.13688324,
       1025.92146812,  272.53426676,  251.80931304,  276.50268399,
        307.10048387,  241.0922911 ,  189.09230206,  650.01657853,
        274.69582134,  804.07722004,  690.49332852,  338.78566994,
        988.359357  ,  660.26997973,  282.2894903 ,  234.00315

In [11]:
len(X_train)

2415

In [12]:
len(y_train)

2415

In [13]:
len(lr.predict(X_train))

2415

In [14]:
print(X_train.shape)

(2415, 3)


In [15]:
print(y_train.shape)

(2415,)


In [16]:
import statsmodels.formula.api as sm
X_opt = X[:, [0, 1, 2]]
lin_reg_OLS = sm.OLS(endog = y, exog = X_opt).fit()
lin_reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 4.157e+07
Date:                Sun, 11 Aug 2019   Prob (F-statistic):               0.00
Time:                        04:11:03   Log-Likelihood:                -6932.5
No. Observations:                3019   AIC:                         1.387e+04
Df Residuals:                    3016   BIC:                         1.389e+04
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.5129      0.014    -36.251      0.000      -0.541      -0.485
x2             0.7401      0.013     56.935      0.000       0.715       0.766
x3             0.7735      0.011     71.476      0.000       0.752       0.795
==============================================================================
Omnibus:                      314.647   Durbin-Watson:                   2.117
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2575.407
Skew:                           0.063   Prob(JB):                         0.00
Kurtosis:                       7.523   Cond. No.                         344.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""